language: ruby
rvm:
  - 2.7.1

notifications:
  email: false

addons:
  postresql: "9.4"

services:
  - redis-server

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database qna_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - 'bundle exec rackup -s puma -E production private_pub.ru &'
  - sleep 3

script:
  - bundle exec rspec --tag ~visual

gemfile:
  - Gemfile
